### PR TITLE
Graceful shutdown

### PR DESCRIPTION
**Pull request by jtpio**
Shutdown kernels on exit (via `KeyboardInterrupt` or `SIGTERM`).

Example:
```
[Voila] Adapting to protocol v5.1 for kernel 6f8d5e1a-5054-471e-9152-70b9400920c1
[Voila] Starting buffering for 6f8d5e1a-5054-471e-9152-70b9400920c1:88e8b607-ef3a-40f0-839d-1849d187d8d2
[Voila] WARNING | Notebook notebooks/basics.ipynb is not trusted
[Voila] Kernel started: 30e6592a-c3c2-482b-8b38-4410677fd360
[Voila] Executing notebook with kernel: python3
[Voila] Adapting to protocol v5.1 for kernel 30e6592a-c3c2-482b-8b38-4410677fd360
^C[Voila] Stopping...
[Voila] Kernel shutdown: b894fdd4-3cde-48c4-b828-3700541d58ea
[Voila] Kernel shutdown: 6f8d5e1a-5054-471e-9152-70b9400920c1
[Voila] Kernel shutdown: 30e6592a-c3c2-482b-8b38-4410677fd360
```

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks, PR looks good, and I can confirm it is working. I rebased this locally, but I cannot (force) push on your branch, can you enable this or rebase it yourself?

**Comment by SylvainCorlay** [comment]
@maartenbreddels if you open another PR with these commits, @jtpio would still be credited for the commits.

**Comment by SylvainCorlay** [comment]
Or @jtpio if you are around that works as well.

**Comment by maartenbreddels** [comment]
Good idea.

**Comment by jtpio** [comment]
https://github.com/QuantStack/voila/pull/65 looks good to me :+1:

**Pull request closed without merging**
