### PR TITLE
WIP: Chore: use css variables

### PR DESCRIPTION
**Pull request by maartenbreddels**
This is a follow up of #153, once that is merged and https://github.com/jupyter-widgets/ipywidgets/pull/2418 + released, we can bump the @jupyter-widgets/jupyterlab-manager version number and have voila with theming support:
image

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Note: if bqplot gets loaded now, the theme changes white, I'm assuming that is expected, since bqplot ships the css variables?

**Comment by SylvainCorlay** [comment]
Yes, I did exactly the same work as this PR yesterday, which triggered

https://github.com/bloomberg/bqplot/pull/855

and the work on removing postcss from ipywidgets.

**Comment by SylvainCorlay** [comment]
Closing since merged #156 with only the removal of postcss.

**Comment by maartenbreddels** [comment]
Ah, I got confused, I thought we need master of ipywidgets, so meaning we also had to bump the version number, but that was not needed. Explains how you got it to work without! :)

**Comment by SylvainCorlay** [comment]
We need master ipywidgets for the bqplot PR, for it to continue working in the classic notebook.

**Pull request closed without merging**
