### PR TITLE
JLab extension: minor fixes 

### PR DESCRIPTION
**Pull request by jtpio**
### Changes

- Add `yarn.lock`
- Update author to `Voila contributors`
- Remove `peerDependencies`

### CODE REVIEW

**Comment by jtpio** [comment]
@SylvainCorlay @maartenbreddels fine for changing the author to "Voila contributors"? (same as for the license)

**Comment by maartenbreddels** [comment]
Fine with me!

(from mobile phone)

**Comment by SylvainCorlay** [comment]
Absolutely

**Comment by jtpio** [comment]
Good :+1:

**Pull request merged**
