### PR TITLE
Setting up testing

### PR DESCRIPTION
**Pull request by maartenbreddels**
This already exposes a bug, voila does not like absolute paths. Good start to setup travis around this.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Note: this needs a rebase.

**Comment by maartenbreddels** [comment]
It passes, but requires pytest<4, which is not ideal, at least it provides us with a small safety net for now.

**Comment by SylvainCorlay** [comment]
Woot!

**Comment by maartenbreddels** [comment]
@timkpaine I'll rebase your PRs, thanks for helping out!

**Pull request merged**
