### PR TITLE
Shut down kernels after running the tests

### PR DESCRIPTION
**Pull request by jtpio**
Fixes https://github.com/QuantStack/voila/issues/231.

Two changes:

- Add a `stop` method to `VoilaApp` to shut down the kernels
- Call that method when in the tests before clearing the `voila_app` instance

It's probably simple enough for now to fix the issue, but we might want to reconsider this approach later on especially regarding `pytest-tornado` (as pointed out by @martinRenou in #231)

### CODE REVIEW

**Comment by martinRenou** [comment]
Mmmmh. Tests are failing on my side. But I would not trust my conda environment this time :P Better trust the CI

**Comment by jtpio** [comment]
Do the tests run in a new fresh environment, after running `python -m pip install ".[test]"` (without the `-e`) and the `test_template`?

**Comment by maartenbreddels** [comment]
LGTM

**Comment by maartenbreddels** [comment]
@martinRenou I'm assuming that is the case indeed :)

**Pull request merged**
