### PR TITLE
Remove gridstack template

### PR DESCRIPTION
**Pull request by SylvainCorlay**
The gridstack template is now installed as a separate package.

```
pip install voila-gridstack
```

### CODE REVIEW

**Comment by timkpaine** [comment]
I have my own template, is there some standardization you want to impose for the pypi projects? Alternatively I can put it on GH then transfer it to you

**Comment by maartenbreddels** [comment]
We now have:
 * voila-gridstack
 * voila-vuetify 
So `voila-<template-name>` for the package name (with dash), and let setuptools do any dash to underscore conversion. Sound good?

**Comment by timkpaine** [comment]
Yep that works

**Comment by SylvainCorlay** [comment]
Thanks.

FYI @timkpaine we just merged a PR changing the custom templates directory from

`PREFIX/share/jupyter/voila/template`

to

`PREFIX/share/jupyter/voila/templates`

which will be part of 0.0.11.

Other then that, your current template should still work in the next version.

**Comment by timkpaine** [comment]
https://github.com/timkpaine/voila-plain

**Comment by timkpaine** [comment]
I just copied the code from the grid stack one and replaced the templates with my own, thanks!

**Comment by timkpaine** [comment]
I added you guys as PyPi maintainers in case the name is too generic and need to take it over in the future.

**Comment by maartenbreddels** [comment]
Great, thanks!
Note/warning: we will most likely break the current template system in the future.

**Comment by SylvainCorlay** [comment]
(To enable progressive rendering and imorove the nbconvert template system.)

**Pull request merged**
