### PR TITLE
Ignore static dir

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I don't think we can ignore the static directory because the `extension.js` file is actually not generated.

**Comment by martinRenou** [comment]
I had some font files in the static dir, is it supposed to be committed too?

**Comment by SylvainCorlay** [comment]
Hum no. are they re-generated if you delete them and rebuild voila?

**Comment by SylvainCorlay** [comment]
Closing in the mean time so that it does not get in in the mean time.

**Comment by martinRenou** [comment]
> Hum no. are they re-generated if you delete them and rebuild voila?

They are not, apparently. I'm not sure where it was coming from then.

**Pull request closed without merging**
